PROGRAM SCORES
IMPLICIT NONE
INTEGER,DIMENSION(10)::A,B
INTEGER::i
A(i) = STUDENT
B(i) = SCORE
B = 85, 62, 95, 91, 38, 74, 55, 88, 61, 47
A = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
CHARACTER(len=1) :: GRADE
CHARACTER(len=12) :: REMARK
PRINT*, 'ENTER STUDENT GRADE:'
READ*, A
DO i=1,10
IF (SCORE(i)>=80) THEN
GRADE = 'A'
REMARK = 'DISTINCTION'
IF (SCORE(i)>=60) THEN
GRADE = 'B'
REMARK = 'CREDIT'
ELSE IF (SCORE(i)>=40) THEN
GRADE = 'C'
REMARK = 'PASS'
ELSE
GRADE = 'F'
REMARK = 'FAIL'
END IF
PRINT'(15,5X,15,5X,A,5X,A)', i, score(i), grade, remark
END DO
END PROGRAM SCORES

!EDWARD_KWAKU_SOLOMON
!6313624
