program test
!AGYIRAKWAH FOSU SAMUEL
!6305724
IMPLICIT NONE
INTEGER::i
INTEGER,DIMENSION(10)::score=(/85,62,45,91,38,74,55,88,61,47)
  
READ*
PRINT*, 'student number , score, grade ,remark'
READ*,student_no,score,grade,remark
DO 
IF ( i>=80) THEN GRADE= 'A' REMARK= 'DISTINCTION'
ELSE IF (i>60)THEN GRADE='B' REMARK='CREDIT'
ELSE IF (i>40)THEN GRADE='C' REMARK='PASS'
ELSE IF (i>0) THEN GRADE='F' REMARK= 'FAIL'
END IF
END PROGRAM test
 
